spring:
  application:
    name: bff-financeiro
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 8085

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

ms-lancamentos:
  url: ${MS_LANCAMENTOS_URL:http://localhost:8083}

ms-centro-custo:
  url: ${MS_CENTRO_CUSTO_URL:http://localhost:8082}

ms-fluxo-caixa:
  url: ${MS_FLUXO_CAIXA_URL:http://localhost:8084}